# Generated by Django 4.2.7 on 2023-11-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=True, help_text='pouvons-nous vous contacter ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_can_be_shared',
            field=models.BooleanField(default=True, help_text='pouvons-nous partager vos données avec nos partenaires ?'),
        ),
    ]
