# Generated by Django 4.2.7 on 2023-12-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_be_contacted_user_data_can_be_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_can_be_shared',
            field=models.BooleanField(default=True),
        ),
    ]
