# Generated by Django 4.2.7 on 2023-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_management', '0002_contributor_unique_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('back-end', 'Backend'), ('front-end', 'Frontend'), ('iOS', 'Ios'), ('android', 'Android')], max_length=10),
        ),
    ]
