# Generated by Django 4.2.7 on 2023-12-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_management', '0004_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
